POST http://localhost:5000/restaurants
Content-Type: application/json

{
    "restaurant_name": "Nourriture",
    "city": "613a75ece8fbec2dffa9da98",
    "tag": "613a7a289641bc46c482dbb2",
    "price_range": "premium",
    "lat": 55.00,
    "lnt": 89.009,
    "phone": "1234567343434",
    "image": "https://blablabla.com",
    "rating": "5/10",
    "website": "https://blablabla.com"
  }